---
- name: Thursday morning challenge
  hosts: bender
  connection: ssh
  gather_facts: no
  become: yes

  vars_prompt:
  - name: mc_server_link
    prompt: "What is the URL to the latest minecraft server?"
    private: no
    default: https://launcher.mojang.com/v1/objects/3cf24a8694aca6267883b17d934efacc5e44440d/server.jar

  tasks:

  - name: Install apps for minecraft server
    block:
        - name: Install additional apps via apt
          apt:
            name:
                    - fail2ban
            state: present

    rescue:
        - name: uninstall apps due to failure
          apt:
            name:
                    - fail2ban
            state: absent

        - fail:
            msg: "Something went wrong when installing these packages!"

  - name: Copy fail2ban (ssh protection)
    copy:
      content: "get off my dang server"
      dest: /etc/fail2ban/jail.conf
    notify:
        - Restart fail2ban

  - name: Add a directory
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/minecraft"
      state: directory

  - name: Download minecraft server
    get_url:
      url: "{{ mc_server_link }}"
      dest: "/home/{{ ansible_user }}/minecraft/minecraft_server.jar"

  handlers:

  - name: Restart fail2ban
    service:
      name: fail2ban
      state: restarted
