---
- name: wednesday warmup
  hosts: looneytunes
  connection: ssh
  gather_facts: no  
  
  tasks:
  
    - name: Create a directory if it does not exist
      file:
      path: /challenge/downloadme.txt
      state: directory
      
    - name: Download file
      get_url:
        url: https://raw.githubusercontent.com/csfeeser/ansible_essentials/main/data/downloadme.txt
        dest: challenge/downloadme.txt

    - name:  make a copy
      copy:
          src: challenge/downloadme.txt
          dest: challenge/downloadme_edit.txt
          force: no
          remote_src:  yes    

    - name: swap PLACEHOLDER for Chad
      replace:
         path: challenge/downloadm_edite.txt"
         regexp: "PLACEHOLDER"
         replace: "Chad"
        


